<a href="https://colab.research.google.com/github/psygrammer/psypy/blob/master/basic/notebooks/04_numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4 NumPy 기본: 배열과 벡터 연산

* 싸이그래머 / PsyPy [1]
* 김무성

In [0]:
!python -V

Python 3.6.8


# 차례
* NumPy란?
* NumPy ndarray : 다차원 배열 객체
  - ndarray 생성하기
  - ndarray의 dtype
  - NumPy 배열의 산술 연산
  - 색인과 슬라이싱 기초
  - 불리언 값으로 선택하기
  - 팬시 색인
  - 배열 전치와 축 바꾸기
* 유니버셜 함수 : 배열의 각 원소를 빠르게 처리하는 함수
* 배열을 이용한 배열지향 프로그래밍
  - 배열 연산으로 조건절 표현하기
  - 수학 메서드와 통계 메서드
  - 불리언 배열을 위한 메서드
  - 정렬
  - 집합 관련 함수
* 배열 데이터의 파일 입출력
* 선형대수
* 난수생성
* 계단 오르내리기 예제

----------------------

# NumPy란?

Numercial Python의 줄임말로 고성능의 과학계산 컴퓨팅과 데이터 분석에 필요한 기본 패키지다. 다음과 같은 기능을 제공한다.

* 빠르고 메모리를 효율적으로 사용하며 벡터 산술연산과 세련된 브로드캐스팅 기능을 제공하는 다차원 배열인 ndarray
* 반복문을 작성할 필요 없이 전체 데이터 배열에 대해 빠른 연산을 제공하는 표준 수학 함수
* 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 올려진 파일을 사용하는 도구
* 선형대수, 난수 발생기, 푸리에 변환 기능
* C, C++, 포트란으로 쓰여진 코드를 통합하는 도구

대부분의 데이터 분석 애플리케이션에서 중요하게 사용되는 기능은 다음과 같다

* 백터 배열상에서 데이터 개조, 정제, 부분 집합, 필터링, 변형, 다른 종류 연산의 빠른 수행
* 정렬, 유일 원소 찾기, 집합연산 같은 일반적인 배열 처리 알고리즘
* 통계의 효과적인 표현과 데이터의 수집/요약
* 다른 종류의 데이터 묶음을 병합하고 엮기 위한 데이터 정렬과 데이터 간의 관계 조작
* if-elif-else를 포함하는 반복문 대신 사용할 수 있는 조건절을 표현할 수 있는 배열 표현
* 데이터 그룹 전체에 적용할 수 있는 수집, 변형, 함수 적용 같은 데이터 처리.

In [0]:
import numpy as np

In [0]:
my_arr = np.arange(1000000)

In [0]:
my_list = list(range(1000000))

In [0]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 17.1 ms, sys: 9.05 ms, total: 26.2 ms
Wall time: 32.1 ms


In [0]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: user 604 ms, sys: 186 ms, total: 791 ms
Wall time: 798 ms


# NumPy ndarray : 다차원 배열 객체
* ndarray 생성하기
* ndarray의 dtype
* NumPy 배열의 산술 연산
* 색인과 슬라이싱 기초
* 불리언 값으로 선택하기
* 팬시 색인
* 배열 전치와 축 바꾸기

### ndarray 특징

* N차원의 배열 객체
* 같은 종류의 데이터만 담을 수 있다(원소는 같은 자료형이여야 한다)
* 모든 배열은 각 차원의 크기를 알려주는 shape라는 튜플과 배열에 저장된 자료형을 알려주는 dtype이라는 객체를 가지고 있다.

In [0]:
import numpy as np

data = np.array([[0.9526, -0.246, -0.8856],
                 [0.5639, 0.2379, 0.9104]])

In [0]:
data * 10

array([[ 9.526, -2.46 , -8.856],
       [ 5.639,  2.379,  9.104]])

In [0]:
data + data

array([[ 1.9052, -0.492 , -1.7712],
       [ 1.1278,  0.4758,  1.8208]])

In [0]:
data.shape

(2, 3)

In [0]:
data.dtype

dtype('float64')

## ndarray 생성하기

In [0]:
# 순차적 객체를 넘겨받아, array 함수를 통해 ndarray를 생성하기
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [0]:
# 같은 길이를 가지는 리스트를 내포하고 있는 순차 데이터는 다차원 배열로 변환 가능하다
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
# data2는 리스트를 담고 있는 리스트이므로 
# NumPy 배열인 arr2는 해당 데이터로부터 형태를 추론하여 2차원 형태로 생성된다.
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [0]:
# 명시적으로 자료형을 지정하지 않는 한 생성될 때 자료형을 추론한다.
print(arr1.dtype)
print(arr2.dtype)

float64
int64


In [0]:
# ndarry를 생성하는 여러 함수와 방식들이 있다.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
np.empty((2, 3, 2))

array([[[2.43862582e-316, 2.33419537e-312],
        [8.48798317e-313, 2.05833592e-312],
        [2.18565567e-312, 9.33678149e-313]],

       [[8.91238232e-313, 2.27053550e-312],
        [2.05833592e-312, 2.18565567e-312],
        [8.70018275e-313, 1.46030983e-319]]])

In [0]:
# 0부터 99까지를 원소로 하는 배열
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [0]:
# 10부터 99
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [0]:
# 0부터 1까지 100단계로
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [0]:
# 로그 스케일로 1부터 10까지 100단계로
np.logspace(0, 1, 100, base=10.0)

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

In [0]:
# 5x5 형식의, 0으로 채워진 배열(이미지) 만들기 
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [0]:
# 5x5x5 형식의, 1로 채워진 배열을 만든다.
# astype() 메서드는 원소들을 정수로 설정한다. 
np.zeros((5,5,5)).astype(int) + 1

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [0]:
# 16비트 부동소수점으로
np.ones((5, 5, 5)).astype(np.float16)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

## ndarray의 dtype

<img src='https://github.com/psygrammer/psypy/blob/master/notebooks/figures/04/02_fig.12.1.png?raw=1'/>

In [0]:
arr = np.ones((10,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
# 배열의 형태를 나타내는 튜플
arr.shape

(10, 5)

In [0]:
# 자료형
arr.dtype

dtype('float64')

In [0]:
# 하나의 원소에서 다음 원소까지의 너비를 표현한 정수를 담고 있는 stride 튜플
# 스트라이드 값은 배열을 복사하지 않고 뷰를 생성하기 위한 필수 값으로 사용된다.
arr.strides

(40, 8)

<img src='https://github.com/psygrammer/psypy/blob/master/notebooks/figures/04/02_fig.12.2.png?raw=1'/>

<img src='https://github.com/psygrammer/psypy/blob/master/notebooks/figures/04/02_tbl.4.2_1.png?raw=1'/>
<img src='https://github.com/psygrammer/psypy/blob/master/notebooks/figures/04/02_tbl.4.2_2.png?raw=1'/>

In [0]:
# dtype은 ndarray가 특정 데이터를 메모리에서 해석하기 위해 필요한 정보를 담고 있는 특수한 객체

arr1 = np.array([1,2,3], dtype=np.float64)
print(arr1)
print(arr1.dtype)

[1. 2. 3.]
float64


In [0]:
arr2 = np.array([1,2,3], dtype=np.int32)
print(arr2)
print(arr2.dtype)

[1 2 3]
int32


In [0]:
# astype 메서드로 배열의 dtype을 다른 형으로 명시적 변경 가능.
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64


## NumPy 배열의 산술 연산

In [0]:
# 배열(ndarry)의 중요한 특징은 for문을 작성하지 않고 데이터를 일괄 처리할 수 있다는 것이다.  
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [0]:
# 더하기
arr + arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [0]:
# 빼기
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
# 곱하기 (개별 원소 곱)
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [0]:
# 스칼라에 대한 산술 연산은 각 요소로 전달
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [0]:
arr * 0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [0]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [0]:
# 같은 크기를 가지는 배열 간의 비교 연산은 불리언 배열을 반환한다.
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [0]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [0]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## 색인과 슬라이싱 기초


In [0]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[5]

5

In [0]:
arr[5:8]

array([5, 6, 7])

In [0]:
# 브로드캐스팅. 배열 슬라이스에 스칼라 값을 대입하면, 그 범위에 값이 전파된다.
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [0]:
# 배열 슬라이스는 값을 복사하는게 아니다. 그러므로 배열 슬라이스의 값을 바꿔도 원본에 반영된다.
arr_slice = arr[5:8] # arr_slice로 arr[5:8]의 값이 복사된게 아님. view의 역할을 할뿐.
arr_slice

array([12, 12, 12])

In [0]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [0]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [0]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [0]:
arr_slice[:] = 64
arr_slice

array([64, 64, 64])

In [0]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [0]:
# 뷰 대신에 슬라이스의 복사본을 얻고 싶다면.
arr_slice_copy = arr[5:8].copy()
print(arr_slice_copy)
print(arr)

[64 64 64]
[ 0  1  2  3  4 64 64 64  8  9]


In [0]:
arr_slice_copy[:] = 8
print(arr_slice_copy)
print(arr)

[8 8 8]
[ 0  1  2  3  4 64 64 64  8  9]


### 다차원 배열

In [0]:
# 2차원 배열
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

0,0 | 0,1 | 0,2
------|--------|--------
1,0 | 1,1 | 1,2
2,0 | 2,1 | 2,2

In [0]:
# 특정 행에 접근
arr2d[2]

array([7, 8, 9])

In [0]:
# 특정 원소에 접근
arr2d[0][2]

3

In [0]:
# 위의 것은 다음과 같이 쓸 수 있다.
arr2d[0,2]

3

In [0]:
# 특정 열 추출
arr2d[:,0]

array([1, 4, 7])

In [0]:
arr2d[:][2]

array([7, 8, 9])

In [0]:
# 3차원 배열
arr3d = np.array([
                  [[1, 2, 3],
                   [4, 5, 6]],
                  [[7, 8, 9],
                   [10, 11, 12]]
                 ])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

0 |  |  | 
------|--------|--------
0,0 | 0,1 | 0,2
1,0 | 1,1 | 1,2
1 |  |  
0,0 | 0,1 | 0,2
1,0 | 1,1 | 1,2

In [0]:
arr3d.shape

(2, 2, 3)

In [0]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [0]:
arr3d[0][1]

array([4, 5, 6])

In [0]:
arr3d[0, 1]

array([4, 5, 6])

In [0]:
arr3d[1][1][2]

12

In [0]:
arr3d[1, 1, 2]

12

In [0]:
arr3d[:, 1, 2]

array([ 6, 12])

#### 슬라이스에 값 넣기

In [0]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [0]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
old_values = arr3d[0].copy() # 원래의 값을 보존하기 위해 복사.

arr3d[0] = 42 # 슬라이스에 스칼라 대입
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [0]:
arr3d[0] = old_values # 슬라이스에 배열 대입 가능(차원이 맞아야 함)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [0]:
# 차원이 맞지 않음
arr3d[0] = np.array([1,2])

ValueError: ignored

### 슬라이스 색인

In [0]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [0]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [0]:
arr2d[1, :2]

array([4, 5])

In [0]:
# 특정 슬라이스 구분에 값을 대입하면 선택 영역 전체에 값이 할당된다.
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 불리언 값으로 선택하기

In [0]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [0]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [0]:
data

array([[ 0.55134636, -1.29683164,  0.78159493, -0.18943033],
       [ 1.67552927, -0.72930364, -0.23399194, -0.3214523 ],
       [-0.39469923, -2.62833496, -1.4411159 ,  2.80382059],
       [ 0.6091548 , -0.23950068, -0.00625523,  0.32690955],
       [-0.2260017 , -0.34822503, -1.9076976 , -0.1885592 ],
       [ 0.2086313 , -0.86229641,  0.75277415, -0.86730902],
       [-0.53630236,  0.8367051 ,  0.22451007,  0.16734691]])

In [0]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [0]:
data[names == 'Bob']

array([[ 0.55134636, -1.29683164,  0.78159493, -0.18943033],
       [ 0.6091548 , -0.23950068, -0.00625523,  0.32690955]])

In [0]:
data[names == 'Bob', 2:]

array([[ 0.78159493, -0.18943033],
       [-0.00625523,  0.32690955]])

In [0]:
data[names == 'Bob', 3]

array([-0.18943033,  0.32690955])

In [0]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [0]:
data[~(names == 'Bob')]

array([[ 1.67552927, -0.72930364, -0.23399194, -0.3214523 ],
       [-0.39469923, -2.62833496, -1.4411159 ,  2.80382059],
       [-0.2260017 , -0.34822503, -1.9076976 , -0.1885592 ],
       [ 0.2086313 , -0.86229641,  0.75277415, -0.86730902],
       [-0.53630236,  0.8367051 ,  0.22451007,  0.16734691]])

In [0]:
cond = names == 'Bob'
data[~cond]

array([[ 1.67552927, -0.72930364, -0.23399194, -0.3214523 ],
       [-0.39469923, -2.62833496, -1.4411159 ,  2.80382059],
       [-0.2260017 , -0.34822503, -1.9076976 , -0.1885592 ],
       [ 0.2086313 , -0.86229641,  0.75277415, -0.86730902],
       [-0.53630236,  0.8367051 ,  0.22451007,  0.16734691]])

In [0]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [0]:
data[mask]

array([[ 0.55134636, -1.29683164,  0.78159493, -0.18943033],
       [-0.39469923, -2.62833496, -1.4411159 ,  2.80382059],
       [ 0.6091548 , -0.23950068, -0.00625523,  0.32690955],
       [-0.2260017 , -0.34822503, -1.9076976 , -0.1885592 ]])

In [0]:
data[data < 0] = 0
data

array([[0.55134636, 0.        , 0.78159493, 0.        ],
       [1.67552927, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 2.80382059],
       [0.6091548 , 0.        , 0.        , 0.32690955],
       [0.        , 0.        , 0.        , 0.        ],
       [0.2086313 , 0.        , 0.75277415, 0.        ],
       [0.        , 0.8367051 , 0.22451007, 0.16734691]])

In [0]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.67552927, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.2086313 , 0.        , 0.75277415, 0.        ],
       [0.        , 0.8367051 , 0.22451007, 0.16734691]])

## 팬시 색인

## 배열 전치와 축 바꾸기

----------------------------